### PR TITLE
fix: test error

### PR DESCRIPTION
**Pull request by ErKeLost**
1. Repair Test error
2. Maybe we can add ci to make sure every test passes. I can provide pr if you like. And can we add some other ci working like farm ci

### CODE REVIEW

**Comment by phoenix-ru** [comment]
Oh, you're quite right! I usually test with `cargo t`, and the test you fixed is for the NAPI integration. I only check that NAPI builds and benches.

Yeah, adding the test pipeline would be great. Maybe it can be a phase in the [`playground`](https://github.com/phoenix-ru/fervid/actions/workflows/playground.yml) workflow? I am not really familiar with GitHub CI and if it's a good idea tbh.

What do you mean by "Farm CI"?

**Comment by ErKeLost** [comment]
> Oh, you're quite right! I usually test with `cargo t`, and the test you fixed is for the NAPI integration. I only check that NAPI builds and benches.
> 
> Yeah, adding the test pipeline would be great. Maybe it can be a phase in the [`playground`](https://github.com/phoenix-ru/fervid/actions/workflows/playground.yml) workflow? I am not really familiar with GitHub CI and if it's a good idea tbh.
> 
> What do you mean by "Farm CI"?

I'm sorry I didn't make it clear. What I meant was that github ci was used to run some necessary tests to prevent unpredictable problems when merging the code. anyway, I think we may access unplugin in the future, so napi should also add js's test guarantee coverage.

**Comment by ErKeLost** [comment]
> > Oh, you're quite right! I usually test with `cargo t`, and the test you fixed is for the NAPI integration. I only check that NAPI builds and benches.
> > 
> > Yeah, adding the test pipeline would be great. Maybe it can be a phase in the [`playground`](https://github.com/phoenix-ru/fervid/actions/workflows/playground.yml) workflow? I am not really familiar with GitHub CI and if it's a good idea tbh.
> > 
> > What do you mean by "Farm CI"?
> 
> I'm sorry I didn't make it clear. What I meant was that github ci was used to run some necessary tests to prevent unpredictable problems when merging the code. anyway, I think we may access unplugin in the future, so napi should also add js's test guarantee coverage.



Recently, I am also studying the vue compiler, and I would like to study with you if I can.

**Comment by ErKeLost** [comment]
Thank you for your suggestion. I will follow your way to learn the compiler of `vue`. I am very interested in `fervid`. I am also looking forward to `fervid's dx` plan and hope to integrate it into `farm` as soon as possible. Thank you.  I also hope that I can learn something about the compiler and finally, if possible, I can help you to develop together.

**Comment by phoenix-ru** [comment]
Hi @ErKeLost :wave: 

How interested are you in contributing to this project? I am a bit wound up with inline mode (this is an optimized mode of compiling SFC when you use `<script setup>`) and don't have time to implement `farm`s CI atm :( But I checked it, it's pretty smart!

To you and anyone interested, I really do appreciate if someone could guide me through setting it up. There are also tests to correct, since I implemented a new parser and it does some things better (notably #6).

**Comment by ErKeLost** [comment]
I am very willing to help with your project and I am very interested in it. I will go back and try to migrate github ci for our project first.

**Pull request merged**
